# Generated by Django 3.1.6 on 2021-03-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('russian-lang', 'Russian language'), ('social-sci', 'Social science'), ('math', 'Mathematics')], max_length=100, unique=True)),
            ],
        ),
    ]
