# Generated by Django 3.1.6 on 2021-03-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('custom_auth', '0002_auto_20210302_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='custom_auth.UserRole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='chat.Subject'),
        ),
    ]
